AWSTemplateFormatVersion: '2010-09-09'
Description: 'Phase 1: SmartRoute Real-Time Data Ingestion - Lambda, SQS, EventBridge'

Parameters:
  ProjectName:
    Type: String
    Default: smartroute
    Description: Project name

  Environment:
    Type: String
    Default: development
    Description: Environment (development/staging/production)

  LambdaMemory:
    Type: Number
    Default: 512
    Description: Lambda function memory in MB

  SQSVisibilityTimeout:
    Type: Number
    Default: 120
    Description: SQS visibility timeout in seconds

  SQSMessageRetentionPeriod:
    Type: Number
    Default: 345600
    Description: SQS message retention period in seconds (default 4 days)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Configuration"
        Parameters:
          - ProjectName
          - Environment
          - LambdaMemory
          - SQSVisibilityTimeout
          - SQSMessageRetentionPeriod

Resources:
  # ==================== SQS Queues ====================

  TransitDataDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-transit-data-dlq'
      MessageRetentionPeriod: 1209600  # 14 days
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  TransitDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ProjectName}-transit-data-queue'
      VisibilityTimeout: !Ref SQSVisibilityTimeout
      MessageRetentionPeriod: !Ref SQSMessageRetentionPeriod
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransitDataDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ==================== MTA Poller Lambda ====================

  MtaPollerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-mta-poller'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-lambda-execution-role'
      Timeout: 60
      MemorySize: !Ref LambdaMemory
      ReservedConcurrentExecutions: 1
      Code:
        ZipFile: |
          # Placeholder - will be replaced with actual code during deployment
          def lambda_handler(event, context):
              return {'statusCode': 200, 'message': 'Placeholder'}
      Environment:
        Variables:
          PROJECT_NAME: !Ref ProjectName
          ENVIRONMENT: !Ref Environment
          S3_BUCKET: !Sub '${ProjectName}-data-lake-${AWS::AccountId}'
          SQS_QUEUE_URL: !Ref TransitDataQueue
          DYNAMODB_TABLE: !Sub '${ProjectName}_station_realtime_state'
          LOG_LEVEL: INFO
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Phase
          Value: '1'

  # ==================== Real-Time Processor Lambda ====================

  RealtimeProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-realtime-processor'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-lambda-execution-role'
      Timeout: 30
      MemorySize: 256
      Code:
        ZipFile: |
          # Placeholder - will be replaced with actual code
          def lambda_handler(event, context):
              return {'statusCode': 200, 'message': 'Placeholder'}
      Environment:
        Variables:
          DYNAMODB_TABLE: !Sub '${ProjectName}_station_realtime_state'
          LOG_LEVEL: INFO
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Phase
          Value: '1'

  # ==================== Event Source Mapping (SQS → Lambda) ====================

  RealtimeProcessorEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt TransitDataQueue.Arn
      FunctionName: !GetAtt RealtimeProcessorFunction.Arn
      Enabled: true
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 5

  # ==================== EventBridge Rules ====================

  MtaPollerScheduleRule:
    Type: AWS::Events::Rule
    DependsOn: MtaPollerFunction
    Properties:
      Name: !Sub '${ProjectName}-mta-poller-schedule'
      Description: Trigger MTA poller every 1 minute
      ScheduleExpression: 'rate(1 minute)'
      State: ENABLED
      Targets:
        - Id: '1'
          Arn: !GetAtt MtaPollerFunction.Arn
          RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-eventbridge-role'
          RetryPolicy:
            MaximumEventAgeInSeconds: 60
            MaximumRetryAttempts: 2

  MtaPollerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MtaPollerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MtaPollerScheduleRule.Arn

  # ==================== CloudWatch Alarms ====================

  MtaPollerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: MtaPollerFunction
    Properties:
      AlarmName: !Sub '${ProjectName}-mta-poller-errors'
      AlarmDescription: Alert on MTA poller Lambda errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref MtaPollerFunction
      TreatMissingData: notBreaching

  MtaPollerDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: MtaPollerFunction
    Properties:
      AlarmName: !Sub '${ProjectName}-mta-poller-duration'
      AlarmDescription: Alert if MTA poller takes too long
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 40000
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref MtaPollerFunction

  SQSApproximateAgeAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: TransitDataQueue
    Properties:
      AlarmName: !Sub '${ProjectName}-sqs-message-age'
      AlarmDescription: Alert if SQS message age is too high
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 60
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt TransitDataQueue.QueueName

  # ==================== CloudWatch Dashboards ====================

  Phase1Dashboard:
    Type: AWS::CloudWatch::Dashboard
    DependsOn:
      - MtaPollerFunction
      - TransitDataQueue
    Properties:
      DashboardName: !Sub '${ProjectName}-phase1-monitoring'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${MtaPollerFunction}", { "stat": "Sum" } ],
                  [ ".", "Errors", "FunctionName", "${MtaPollerFunction}", { "stat": "Sum" } ],
                  [ ".", "Duration", "FunctionName", "${MtaPollerFunction}", { "stat": "Average" } ]
                ],
                "period": 60,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "MTA Poller Lambda Metrics"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  [ "AWS/SQS", "ApproximateAgeOfOldestMessage", "QueueName", "${TransitDataQueue.QueueName}", { "stat": "Maximum" } ],
                  [ ".", "ApproximateNumberOfMessagesVisible", "QueueName", "${TransitDataQueue.QueueName}", { "stat": "Sum" } ],
                  [ ".", "NumberOfMessagesSent", "QueueName", "${TransitDataQueue.QueueName}", { "stat": "Sum" } ]
                ],
                "period": 60,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "SQS Queue Metrics"
              }
            }
          ]
        }

  # ==================== Log Retention ====================

  MtaPollerLogRetention:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-mta-poller'
      RetentionInDays: 14

  RealtimeProcessorLogRetention:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-realtime-processor'
      RetentionInDays: 14

Outputs:
  TransitDataQueueArn:
    Description: SQS Queue ARN
    Value: !GetAtt TransitDataQueue.Arn
    Export:
      Name: !Sub '${ProjectName}-sqs-queue-arn'

  TransitDataQueueUrl:
    Description: SQS Queue URL
    Value: !Ref TransitDataQueue
    Export:
      Name: !Sub '${ProjectName}-sqs-queue-url'

  TransitDataDLQArn:
    Description: SQS Dead Letter Queue ARN
    Value: !GetAtt TransitDataDLQ.Arn
    Export:
      Name: !Sub '${ProjectName}-sqs-dlq-arn'

  MtaPollerFunctionArn:
    Description: MTA Poller Lambda ARN
    Value: !GetAtt MtaPollerFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-mta-poller-arn'

  MtaPollerFunctionName:
    Description: MTA Poller Lambda Name
    Value: !Ref MtaPollerFunction
    Export:
      Name: !Sub '${ProjectName}-mta-poller-name'

  RealtimeProcessorFunctionArn:
    Description: Real-time Processor Lambda ARN
    Value: !GetAtt RealtimeProcessorFunction.Arn
    Export:
      Name: !Sub '${ProjectName}-realtime-processor-arn'

  RealtimeProcessorFunctionName:
    Description: Real-time Processor Lambda Name
    Value: !Ref RealtimeProcessorFunction
    Export:
      Name: !Sub '${ProjectName}-realtime-processor-name'
