AWSTemplateFormatVersion: '2010-09-09'
Description: 'SmartRoute Phase 2 - Analytics with Glue and Athena'

Parameters:
  DataLakeBucket:
    Type: String
    Default: smartroute-data-lake-069899605581
  
  GlueDatabaseName:
    Type: String
    Default: smartroute_analytics

Resources:
  # Glue Database for Analytics
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref GlueDatabaseName
        Description: SmartRoute analytics and metrics database
        Parameters:
          classification: parquet

  # IAM Role for Glue
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DataLakeBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DataLakeBucket}'
        - PolicyName: GlueAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:*
                Resource: '*'
        - PolicyName: LogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  # Glue Crawler for raw vehicle data
  VehicleDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: smartroute-vehicle-data-crawler
      DatabaseName: !Ref GlueDatabaseName
      Role: !GetAtt GlueServiceRole.Arn
      Targets:
        S3Targets:
          - Path: !Sub 's3://${DataLakeBucket}/raw/mta/realtime'
            Exclusions:
              - '**/_SUCCESS'
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Schedule:
        ScheduleExpression: 'cron(0 * * * ? *)'  # Every hour

  # Athena Query Results Bucket
  AthenaResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'smartroute-athena-results-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldQueryResults
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Athena WorkGroup for analytics queries
  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: smartroute-analytics
      RecursiveDeleteOption: true
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub 's3://${AthenaResultsBucket}/results/'
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        BytesScannedCutoffPerQuery: 10737418240  # 10GB limit

  # Output: Export values for reference
Outputs:
  GlueDatabaseName:
    Description: Glue Database for analytics
    Value: !Ref GlueDatabaseName
    Export:
      Name: !Sub '${AWS::StackName}-GlueDatabaseName'
  
  AthenaWorkGroupName:
    Description: Athena WorkGroup for queries
    Value: !Ref AthenaWorkGroup
    Export:
      Name: !Sub '${AWS::StackName}-AthenaWorkGroup'
  
  AthenaResultsBucket:
    Description: S3 bucket for Athena query results
    Value: !Ref AthenaResultsBucket
    Export:
      Name: !Sub '${AWS::StackName}-AthenaResultsBucket'

